"""Add PTZ presets and patrol patterns tables

Revision ID: 4b2aa0a5583c
Revises: f6ac4ba2cc1d
Create Date: 2025-10-31 12:09:51.341603

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4b2aa0a5583c'
down_revision: Union[str, Sequence[str], None] = 'f6ac4ba2cc1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ptz_patrol_patterns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('pattern_steps', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('loop_enabled', sa.Boolean(), nullable=True),
    sa.Column('interval_seconds', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_run_at', sa.DateTime(), nullable=True),
    sa.Column('run_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ptz_patrol_patterns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ptz_patrol_patterns_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ptz_patrol_patterns_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ptz_patrol_patterns_is_active'), ['is_active'], unique=False)

    op.create_table('ptz_presets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('preset_number', sa.Integer(), nullable=False),
    sa.Column('pan', sa.Float(), nullable=False),
    sa.Column('tilt', sa.Float(), nullable=False),
    sa.Column('zoom', sa.Float(), nullable=False),
    sa.Column('thumbnail_path', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('ptz_presets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_ptz_presets_camera_id'), ['camera_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_ptz_presets_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ptz_presets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ptz_presets_id'))
        batch_op.drop_index(batch_op.f('ix_ptz_presets_camera_id'))

    op.drop_table('ptz_presets')
    with op.batch_alter_table('ptz_patrol_patterns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_ptz_patrol_patterns_is_active'))
        batch_op.drop_index(batch_op.f('ix_ptz_patrol_patterns_id'))
        batch_op.drop_index(batch_op.f('ix_ptz_patrol_patterns_camera_id'))

    op.drop_table('ptz_patrol_patterns')
    # ### end Alembic commands ###
