"""Add motion_zones table for zone-based motion detection

Revision ID: 5eeed29fa758
Revises: 9057848527e7
Create Date: 2025-10-26 02:09:01.898705

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.database.migration_guards import (
    add_column_if_missing,
    create_index_if_missing,
    create_table_if_missing,
)



# revision identifiers, used by Alembic.
revision: str = '5eeed29fa758'
down_revision: Union[str, Sequence[str], None] = '9057848527e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    create_table_if_missing('motion_zones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('camera_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('zone_type', sa.String(), nullable=True),
    sa.Column('coordinates', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_exclusion_zone', sa.Boolean(), nullable=True),
    sa.Column('sensitivity_multiplier', sa.Float(), nullable=True),
    sa.Column('color', sa.String(), nullable=True),
    sa.Column('opacity', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('motion_events_count', sa.Integer(), nullable=True),
    sa.Column('last_motion_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['camera_id'], ['cameras.camera_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    create_index_if_missing(op.f('ix_motion_zones_camera_id'), 'motion_zones', ['camera_id'], unique=False)
    create_index_if_missing(op.f('ix_motion_zones_id'), 'motion_zones', ['id'], unique=False)
    create_index_if_missing(op.f('ix_motion_zones_is_active'), 'motion_zones', ['is_active'], unique=False)

    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.alter_column('shadow_detection_method',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True,
               existing_server_default=sa.text("'dual'"))
        batch_op.alter_column('use_grayscale',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('lighting_compensation_enabled',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))

    with op.batch_alter_table('face_clusters', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_cluster_identified'))
        batch_op.drop_index(batch_op.f('idx_cluster_updated'))

    with op.batch_alter_table('face_detection_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_face_camera_time'))
        batch_op.drop_index(batch_op.f('idx_face_cluster_time'))
        batch_op.drop_index(batch_op.f('idx_face_person_time'))

    with op.batch_alter_table('motion_detection_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_motion_camera_time'))
        batch_op.drop_index(batch_op.f('idx_motion_detected_at'))

    with op.batch_alter_table('recording_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_recording_camera_time'))
        batch_op.drop_index(batch_op.f('idx_recording_started_at'))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('two_factor_enrolled_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('two_factor_enrolled_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)

    create_index_if_missing(op.f('idx_recording_started_at'), 'recording_events', ['started_at'], unique=False)
    create_index_if_missing(op.f('idx_recording_camera_time'), 'recording_events', ['camera_id', 'started_at'], unique=False)

    create_index_if_missing(op.f('idx_motion_detected_at'), 'motion_detection_events', ['detected_at'], unique=False)
    create_index_if_missing(op.f('idx_motion_camera_time'), 'motion_detection_events', ['camera_id', 'detected_at'], unique=False)

    create_index_if_missing(op.f('idx_face_person_time'), 'face_detection_events', ['person_name', 'detected_at'], unique=False)
    create_index_if_missing(op.f('idx_face_cluster_time'), 'face_detection_events', ['cluster_id', 'detected_at'], unique=False)
    create_index_if_missing(op.f('idx_face_camera_time'), 'face_detection_events', ['camera_id', 'detected_at'], unique=False)

    create_index_if_missing(op.f('idx_cluster_updated'), 'face_clusters', ['updated_at'], unique=False)
    create_index_if_missing(op.f('idx_cluster_identified'), 'face_clusters', ['is_identified'], unique=False)

    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.alter_column('lighting_compensation_enabled',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('use_grayscale',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('shadow_detection_method',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'dual'"))

    with op.batch_alter_table('motion_zones', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_motion_zones_is_active'))
        batch_op.drop_index(batch_op.f('ix_motion_zones_id'))
        batch_op.drop_index(batch_op.f('ix_motion_zones_camera_id'))

    op.drop_table('motion_zones')
    # ### end Alembic commands ###
