"""Add overlay settings to cameras table

Revision ID: f6ac4ba2cc1d
Revises: 5eeed29fa758
Create Date: 2025-10-31 11:45:11.971899

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.database.migration_guards import (
    add_column_if_missing,
    create_index_if_missing,
    create_table_if_missing,
)



# revision identifiers, used by Alembic.
revision: str = 'f6ac4ba2cc1d'
down_revision: Union[str, Sequence[str], None] = '5eeed29fa758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    add_column_if_missing('cameras', sa.Column('overlay_enabled', sa.Boolean(), nullable=True))
    add_column_if_missing('cameras', sa.Column('overlay_timestamp_enabled', sa.Boolean(), nullable=True))
    add_column_if_missing('cameras', sa.Column('overlay_custom_text', sa.String(), nullable=True))
    add_column_if_missing('cameras', sa.Column('overlay_position', sa.String(), nullable=True))
    add_column_if_missing('cameras', sa.Column('overlay_font_size', sa.Integer(), nullable=True))
    add_column_if_missing('cameras', sa.Column('overlay_font_color', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cameras', schema=None) as batch_op:
        batch_op.drop_column('overlay_font_color')
        batch_op.drop_column('overlay_font_size')
        batch_op.drop_column('overlay_position')
        batch_op.drop_column('overlay_custom_text')
        batch_op.drop_column('overlay_timestamp_enabled')
        batch_op.drop_column('overlay_enabled')

    # ### end Alembic commands ###
