#!/usr/bin/env python3
"""
Automated Notification Encryption Key Setup

Generates and adds NOTIFICATION_ENCRYPTION_KEY to .env file automatically.
Safe to run multiple times - preserves existing key if found.
"""

import sys
from pathlib import Path
from cryptography.fernet import Fernet
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)


def find_env_file():
    """Find .env file in opencv_surveillance directory"""
    # Script is in opencv_surveillance/scripts/
    script_dir = Path(__file__).parent
    opencv_dir = script_dir.parent
    env_path = opencv_dir / '.env'

    return env_path


def read_env_file(env_path):
    """Read .env file contents"""
    if not env_path.exists():
        logger.info(f".env file not found at {env_path}")
        return []

    with open(env_path, 'r') as f:
        return f.readlines()


def has_encryption_key(lines):
    """Check if NOTIFICATION_ENCRYPTION_KEY already exists"""
    for line in lines:
        stripped = line.strip()
        if stripped.startswith('NOTIFICATION_ENCRYPTION_KEY='):
            # Extract the value
            value = stripped.split('=', 1)[1]
            # Check if it's not empty or a placeholder
            if value and value not in ['<generate>', '<your-key>', '']:
                return True, value
    return False, None


def generate_encryption_key():
    """Generate a new Fernet encryption key"""
    key = Fernet.generate_key()
    return key.decode()


def add_key_to_env(env_path, lines, key):
    """Add encryption key to .env file"""
    # Find if NOTIFICATION_ENCRYPTION_KEY line exists (empty or placeholder)
    key_line_index = None
    for i, line in enumerate(lines):
        if line.strip().startswith('NOTIFICATION_ENCRYPTION_KEY='):
            key_line_index = i
            break

    # Create the new key line
    new_key_line = f"NOTIFICATION_ENCRYPTION_KEY={key}\n"

    if key_line_index is not None:
        # Replace existing line
        lines[key_line_index] = new_key_line
        logger.info("Updated existing NOTIFICATION_ENCRYPTION_KEY line")
    else:
        # Add new line
        # Find a good place to insert (after other keys, or at end)
        insert_index = len(lines)

        # Try to insert after SECRET_KEY or JWT_SECRET_KEY
        for i, line in enumerate(lines):
            if 'SECRET_KEY' in line or 'JWT_SECRET_KEY' in line:
                insert_index = i + 1

        # Add a comment if inserting in the middle
        if insert_index < len(lines):
            lines.insert(insert_index, "\n")
            lines.insert(insert_index + 1, "# Notification Provider Credential Encryption\n")
            lines.insert(insert_index + 2, new_key_line)
        else:
            # Adding at end
            if lines and not lines[-1].endswith('\n'):
                lines.append('\n')
            lines.append('\n')
            lines.append('# Notification Provider Credential Encryption\n')
            lines.append(new_key_line)

        logger.info("Added NOTIFICATION_ENCRYPTION_KEY to .env file")

    return lines


def write_env_file(env_path, lines):
    """Write updated .env file"""
    with open(env_path, 'w') as f:
        f.writelines(lines)


def create_env_file_with_key(env_path, key):
    """Create new .env file with encryption key"""
    logger.info(f"Creating new .env file at {env_path}")

    content = f"""# OpenEye Environment Configuration
# Generated by setup_notification_encryption.py

# Security Keys (REQUIRED in production)
SECRET_KEY=dev-secret-key-change-in-production
JWT_SECRET_KEY=dev-jwt-key-change-in-production

# Notification Provider Credential Encryption
NOTIFICATION_ENCRYPTION_KEY={key}

# Database (optional - defaults to SQLite)
DATABASE_URL=sqlite:///./surveillance.db

# CORS (optional)
CORS_ORIGINS=http://localhost:8000,http://localhost:3000,http://127.0.0.1:8000,http://127.0.0.1:3000

# Features (optional - all enabled by default)
ENABLE_MOTION_DETECTION=true
ENABLE_FACE_RECOGNITION=true
ENABLE_RECORDING=true

# Logging
LOG_LEVEL=INFO
"""

    with open(env_path, 'w') as f:
        f.write(content)


def setup_encryption_key():
    """Main setup function"""
    logger.info("=" * 70)
    logger.info("Notification Encryption Key Setup")
    logger.info("=" * 70)

    # Find .env file
    env_path = find_env_file()
    logger.info(f"Looking for .env at: {env_path}")

    # Read existing .env or create new
    if env_path.exists():
        lines = read_env_file(env_path)

        # Check if key already exists
        has_key, existing_key = has_encryption_key(lines)

        if has_key:
            logger.info("✅ NOTIFICATION_ENCRYPTION_KEY already configured!")
            logger.info(f"   Key: {existing_key[:16]}...{existing_key[-16:]}")
            logger.info("   Skipping key generation (existing key preserved)")
            return existing_key

        # Generate new key
        logger.info("Generating new encryption key...")
        new_key = generate_encryption_key()

        # Add to .env
        updated_lines = add_key_to_env(env_path, lines, new_key)
        write_env_file(env_path, updated_lines)

        logger.info("✅ Encryption key added to .env file")
        logger.info(f"   Key: {new_key[:16]}...{new_key[-16:]}")

    else:
        # Create new .env file
        logger.info("No .env file found - creating new one")
        new_key = generate_encryption_key()
        create_env_file_with_key(env_path, new_key)

        logger.info("✅ Created .env file with encryption key")
        logger.info(f"   Location: {env_path}")
        logger.info(f"   Key: {new_key[:16]}...{new_key[-16:]}")

    logger.info("")
    logger.info("=" * 70)
    logger.info("Setup Complete!")
    logger.info("=" * 70)
    logger.info("")
    logger.info("⚠️  IMPORTANT SECURITY NOTES:")
    logger.info("   1. Never commit .env files to version control")
    logger.info("   2. Use different keys for dev/production environments")
    logger.info("   3. Changing this key will invalidate all existing credentials")
    logger.info("   4. Back up this key in a secure location")
    logger.info("")
    logger.info("Next steps:")
    logger.info("   1. Restart the backend server")
    logger.info("   2. Navigate to Settings → Notifications in the web UI")
    logger.info("   3. Configure your notification providers")
    logger.info("=" * 70)

    return new_key


if __name__ == "__main__":
    try:
        setup_encryption_key()
        sys.exit(0)
    except Exception as e:
        logger.error(f"❌ Setup failed: {e}")
        logger.exception(e)
        sys.exit(1)
